version: "3"
services:
  sender:
    build:
      context: ./sender
    container_name: sender
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      - ./sender/data:/data
    environment:
      - DISPLAY=:0